version: '3'

services:
  message-service:
    image: hub.imooc.com:11111/micro-service/message-thrift:latest
    environment:
      # 邮箱密码在环境变量中
      MAIL_PASS: ${MAIL_PASS}

  user-service:
    image: hub.imooc.com:11111/micro-service/user-service:latest
    environment:
      # 这是mysql的地址
      MYSQL_ADDRESS: "192.168.0.113"

  user-edge-service:
    image: hub.imooc.com:11111/micro-service/user-edge-service:latest
    depends_on:
      - user-service
    environment:
      # 这是mysql的地址
      REDIS_HOST: "192.168.0.110"

  course-dubbo-service:
    image: hub.imooc.com:11111/micro-service/course-dubbo-service:latest
    environment:
      MYSQL_ADDRESS: "192.168.0.113"
      ZOOKEEPER_HOST: "192.168.0.110"
    ports:
      - 20880:20880
    depends_on:
      - user-service

  course-edge-service:
    image: hub.imooc.com:11111/micro-service/course-edge-service:latest
    depends_on:
      - course-dubbo-service
    environment:
      ZOOKEEPER_HOST: "192.168.0.110"

  api-gateway-zuul:
    image: hub.imooc.com:11111/micro-service/api-gateway-zuul:latest
    ports:
      - 8889:8889






