version: '3'

services:
  zookeeper:
    image: zookeeper:3.5

  message-service:
    image: hub.wktadmin.com:11111/micro-service/message-thrift:latest
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"
    environment:
      # 邮箱密码在环境变量中
      MAIL_PASS: ${MAIL_PASS}

  user-service:
    image: hub.wktadmin.com:11111/micro-service/user-service:latest
    environment:
      # 这是mysql的地址
      MYSQL_ADDRESS: ${MYSQL_ADDRESS}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"

  user-edge-service:
    image: hub.wktadmin.com:11111/micro-service/user-edge-service:latest
    depends_on:
      - user-service
      - message-service
    environment:
      # 这是mysql的地址
      REDIS_HOST: ${REDIS_HOST}

  course-dubbo-service:
    image: hub.wktadmin.com:11111/micro-service/course-dubbo-service:latest
    environment:
      MYSQL_ADDRESS: ${MYSQL_ADDRESS}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 20880:20880
    depends_on:
      - zookeeper
      - user-service

  course-edge-service:
    image: hub.wktadmin.com:11111/micro-service/course-edge-service:latest
    depends_on:
      - course-dubbo-service
    command: ["./wait-for-it.sh", "course-dubbo-service:8089", "--", "sleep", "5;", "java", "-jar", "/course-edge-service.jar"]

  api-gateway-zuul:
    image: hub.wktadmin.com:11111/micro-service/api-gateway-zuul:latest
    ports:
      - 8889:8889
    depends_on:
      - user-edge-service
      - course-edge-service





