version: '3'

services:
  zookeeper:
    image: zookeeper:3.5

  message-service:
    image: hub.imooc.com:11111/micro-service/message-thrift:latest
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"
    environment:
      # 邮箱密码在环境变量中
      MAIL_PASS: ${MAIL_PASS}

  user-service:
    image: hub.imooc.com:11111/micro-service/user-service:latest
    environment:
      # 这是mysql的地址
      MYSQL_ADDRESS: "10.0.75.1"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"

  user-edge-service:
    image: hub.imooc.com:11111/micro-service/user-edge-service:latest
    depends_on:
      - user-service
    environment:
      # 这是mysql的地址
      REDIS_HOST: "10.0.75.1"

  course-dubbo-service:
    image: hub.imooc.com:11111/micro-service/course-dubbo-service:latest
    environment:
      MYSQL_ADDRESS: "10.0.75.1"
    ports:
      - 20880:20880
    depends_on:
      - zookeeper
      - user-service

  course-edge-service:
    image: hub.imooc.com:11111/micro-service/course-edge-service:latest
    depends_on:
      - course-dubbo-service

  api-gateway-zuul:
    image: hub.imooc.com:11111/micro-service/api-gateway-zuul:latest
    ports:
      - 8889:8889





